openapi: 3.0.3
info:
  title: LabWork API
  description: |-
    Сервис ориентированная архитектура. Лабораторная №1
  version: 1.0.0
servers:
  - url: https://se.ifmo.ru/~s283945/soa/bars
tags:
  - name: discipline
    description: Everything about labs
paths:
  /discipline/{discipline-id}/labwork/{labwork-id}/add:
    post: 
      tags:
        - discipline
      summary: Add lab to discipline
      operationId: addLabToDiscipline
      parameters:
        - name: discipline-id
          in: path
          description: Set discipline id
          required: true
          schema:
            type: integer
        - name: labwork-id
          in: path
          description: Set lab work id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation. Returns added lab
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lab'   
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse' 
        '500':
          description: Validation exception
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse' 
  /discipline/{discipline-id}/make-hardcore:
    put: 
      tags:
        - discipline
      summary: Add 10 hardcore labs to discipline
      operationId: addHardcoreLabToDiscipline
      parameters:
        - name: discipline-id
          in: path
          description: Set discipline id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation. Returns added lab
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lab'   
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse' 
        '500':
          description: Validation exception
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse' 
components:
  schemas:
    Lab:
      type: object
      required: 
        - name
        - coordinates
        - creationDate
        - minimalPoint
        - personalQualitiesMaximum
        - description
        - difficulty
        - discipline
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Service oriented architecture
        coordinates:
           $ref: '#/components/schemas/Coordinates'
        creationDate:
          type: string
          format: date-time
          example: "Wed Mar 27 08:22:02 IST 2015"
        minimalPoint:
          type: integer
          format: int64
          example: 6
          description: value should me more then 0
        personalQualitiesMaximum:
          type: number
          format: float
          example: 2
          description: value should me more then 0
        difficulty:
          $ref: '#/components/schemas/Difficulty'
        discipline:
          $ref: '#/components/schemas/Discipline'
      xml:
        name: order
    Coordinates:
      type: object
      required: 
        - x
      properties:
        x:
          type: number
          format: double
          example: 1.2
          description: value should me less then 295
        y:
          type: number
          format: double
          example: 1.2
          description: value should me less then 850
    Difficulty:
      type: string
      enum: 
        - VERY_EASY
        - NORMAL
        - VERY_HARD
        - IMPOSSIBLE
        - INSANE
    Discipline :
      type: object
      required:
        - name
        - selfStudyHours
      properties:
        name:
          type: string
          example: Service Oriented Architecture
        lectureHours:
          type: integer
          format: int32
          example: 2
        selfStudyHours:
          type: integer
          format: int32
          example: 2
      xml:
        name: address
    # LabFields:
    #   type: string
    #   enum:
    #     - name
    #     - x
    #     - y
    #     - creationDate
    #     - minimalPoint
    #     - personalQualitiesMaximum
    #     - description
    #     - difficulty
    #     - disciplineName
    #     - disciplineLectureHours
    #     - disciplineSelfStudyHours
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:
    Lab:
      description: Lab object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Lab'
        application/xml:
          schema:
            $ref: '#/components/schemas/Lab'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []